set encoding=utf-8

set nocompatible              
filetype off
" search down into subfolders while using :open
set path+=**
" yaml highlight
au BufNewFile,BufRead *.yaml,*.yml so ~/.vim/yaml.vim

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'tmhedberg/SimpylFold'
Plugin 'nvie/vim-flake8'
"Bundle 'Valloric/YouCompleteMe'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

call vundle#end()
filetype plugin indent on

let python_highlight_all=1
syntax on
:color desert

" Enable folding
"set foldmethod=indent
"set foldlevel=99

" Enable folding with the spacebar
nnoremap <space> za

" au BufNewFile,BufRead *.js, *.html, *.css
"     \ set tabstop=2 |
"     \ set softtabstop=2 | 
"     \ set shiftwidth= 

" YouCompleteMe customizations
"let g:ycm_autoclose_preview_window_after_completion=1
"map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>

set pastetoggle=<F3>
